{{- if .Values.logging.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "django-app.fullname" . }}-fluentbit-parsers
  namespace: {{ .Release.Namespace }}
data:
  parsers.conf: |
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On
        Decode_Field_As   escaped_utf8    log
        Decode_Field_As   json            log
{{- end }}
