{{- if .Values.logging.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "django-app.fullname" . }}-fluentbit
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "django-app.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ include "django-app.name" . }}-fluentbit
  template:
    metadata:
      labels:
        app: {{ include "django-app.name" . }}-fluentbit
    spec:
      containers:
      - name: fluent-bit
        image: fluent/fluent-bit:2.2
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: fluentbit-config
          mountPath: /fluent-bit/etc/
        - name: varlog
          mountPath: /var/log
          readOnly: true
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluentbit-state
          mountPath: /var/log/fluentbit-state
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
      volumes:
      - name: fluentbit-config
        configMap:
          name: {{ include "django-app.fullname" . }}-fluentbit
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluentbit-state
        hostPath:
          path: /var/log/fluentbit-state
          type: DirectoryOrCreate
      serviceAccountName: default
      tolerations:
      - operator: Exists
{{- end }}
