{{- if .Values.app.secret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "django-app.fullname" . }}-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "django-app.labels" . | nindent 4 }}
type: Opaque
data:
  {{- toYaml .Values.app.secret | nindent 2 }}
{{- end }}
